site_name: Notionary
site_url: https://mathisarends.github.io/notionary/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    - scheme: default
      primary: black
      accent: indigo

extra_css:
  - assets/styles.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            heading_level: 2
            members_order: source
            show_signature_annotations: true
            separate_signature: true
            docstring_style: google
            merge_init_into_class: true
            show_if_no_docstring: false

nav:
  - Intro: intro.md
  - Quickstart: quickstart.md

  - Guides:
      - Page: page.md
      - Database: database.md
      - Data Source: data_source/index.md
      - File Upload: file_upload/index.md
      - Workspace: workspace/index.md

  - API Reference:
      - Notionary: api/notionary.md
      - Page: api/page.md
      - Database: api/database.md
      - Data Source: api/data_source.md
      - File Uploads: api/file_uploads.md
      - Users: api/users.md
      - Workspace: api/workspace.md
      - Exceptions: api/exceptions.md

  - Contributing: contributing.md

repo_url: https://github.com/mathisarends/notionary
repo_name: mathisarends/notionary

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
