[project]
name = "notionary"
version = "0.2.14"
description = "A toolkit to convert between Markdown and Notion blocks"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Mathis Arends", email = "mathisarends27@gmail.com" }
]
license = { text = "MIT" }
dependencies = [
    "httpx>=0.28.0",
    "python-dotenv>=1.1.0",
    "pydantic>=2.11.4",
    "click>=8.0.0",
]

[project.urls]
Homepage = "https://github.com/mathisarends/notionary"

[project.scripts]
notionary = "notionary.cli.main:main"

[tool.poetry.group.dev.dependencies]
mkdocs = "^1.6.1"
mkdocs-material = "^9.6.15"

