"""
Markdown module for Notionary.

This module provides classes and utilities for working with Markdown content,
including builders, model processors, and parameter types.
"""

from __future__ import annotations

from .markdown_document_model import (
    MarkdownDocumentModel,
    MarkdownBlock,
    HeadingBlock,
    ParagraphBlock,
    QuoteBlock,
    BulletedListBlock,
    NumberedListBlock,
    TodoBlock,
    CalloutBlock,
    CodeBlock,
    ImageBlock,
    VideoBlock,
    AudioBlock,
    FileBlock,
    PdfBlock,
    BookmarkBlock,
    EmbedBlock,
    TableBlock,
    DividerBlock,
    EquationBlock,
    TableOfContentsBlock,
    ToggleBlock,
    ToggleableHeadingBlock,
    ColumnBlock,
)
from .markdown_node import MarkdownNode

from .block_params import (
    AudioProcessorModel,
    BookmarkProcessorModel,
    BreadcrumbProcessorModel,
    BulletedListProcessorModel,
    CalloutProcessorModel,
    CodeProcessorModel,
    ColumnProcessorModel,
    DividerProcessorModel,
    EmbedProcessorModel,
    EquationProcessorModel,
    FileProcessorModel,
    HeadingProcessorModel,
    ImageProcessorModel,
    NumberedListProcessorModel,
    ParagraphProcessorModel,
    PdfProcessorModel,
    QuoteProcessorModel,
    TableProcessorModel,
    TableOfContentsProcessorModel,
    TodoProcessorModel,
    ToggleProcessorModel,
    ToggleableHeadingProcessorModel,
    VideoProcessorModel,
)

__all__ = [
    # Core classes
    "MarkdownDocumentModel",
    "MarkdownNode",
    # Document model blocks
    "MarkdownBlock",
    "HeadingBlock",
    "ParagraphBlock",
    "QuoteBlock",
    "BulletedListBlock",
    "NumberedListBlock",
    "TodoBlock",
    "CalloutBlock",
    "CodeBlock",
    "ImageBlock",
    "VideoBlock",
    "AudioBlock",
    "FileBlock",
    "PdfBlock",
    "BookmarkBlock",
    "EmbedBlock",
    "TableBlock",
    "DividerBlock",
    "EquationBlock",
    "TableOfContentsBlock",
    "ToggleBlock",
    "ToggleableHeadingBlock",
    "ColumnBlock",
    # Parameter types
    "AudioProcessorModel",
    "BookmarkProcessorModel",
    "BreadcrumbProcessorModel",
    "BulletedListProcessorModel",
    "CalloutProcessorModel",
    "CodeProcessorModel",
    "ColumnProcessorModel",
    "DividerProcessorModel",
    "EmbedProcessorModel",
    "EquationProcessorModel",
    "FileProcessorModel",
    "HeadingProcessorModel",
    "ImageProcessorModel",
    "NumberedListProcessorModel",
    "ParagraphProcessorModel",
    "PdfProcessorModel",
    "QuoteProcessorModel",
    "TableProcessorModel",
    "TableOfContentsProcessorModel",
    "TodoProcessorModel",
    "ToggleProcessorModel",
    "ToggleableHeadingProcessorModel",
    "VideoProcessorModel",
]
